### ISSUE TITLE
New extractor for ASM 12.1

### ISSUE THREAD

**Issue by lysacor** [jeremymcgee73/Graylog_Content_Pack_BIGIP_ASM#2]
I would do a pull request, but I put together a modified version of the string used in the extractor for the message. Here is what I came up with and it seems to work in Graylog 2.3 with all requests being logged.

ASM:unit_hostname="%{DATA:unit_hostname}",management_ip_address="%{DATA:management_ip_address}",http_class_name="%{DATA:http_class_name}",web_application_name="%{DATA:web_application_name}",policy_name="%{DATA:policy_name}",policy_apply_date="%{DATA:policy_apply_date}",violations="%{DATA:violations}",support_id="%{DATA:support_id}",request_status="%{DATA:request_status}",response_code="%{DATA:response_code}",ip_client="%{DATA:ip_client}",route_domain="%{DATA:route_domain}",method="%{DATA:method}",protocol="%{DATA:protocol}",query_string="%{DATA:query_string}",x_forwarded_for_header_value="%{DATA:x-forwarded-for}",sig_ids="%{DATA:sig_ids}",sig_names="%{DATA:sig_names}",date_time="%{DATA:timestamp;date;yyyy-MM-dd HH:mm:ss}",severity="%{DATA:severity}",attack_type="%{DATA:attack_type}",geo_location="%{DATA:geo_location}",ip_address_intelligence="%{DATA:ip_address_intelligence}",username="%{DATA:username}",session_id="%{DATA:session_id}",src_port="%{DATA:src_port}",dest_port="%{DATA:dest_port}",dest_ip="%{DATA:dest_ip}",sub_violations="%{DATA:sub_violations}",virus_name="%{DATA:virus_name}",violation_rating="%{DATA:violation_rating}",websocket_direction="%{DATA:websocket_direction}",websocket_message_type="%{DATA:websocket_message_type}",device_id="%{DATA:device_id}",uri="%{DATA:uri}",request="%{DATA:request}"

**Comment by jeremymcgee73** [comment]
Awesome thank you! I will merge this. I actually wrote something very similar awhile back. But, I had to start using logstash in front of graylog, so my log parsing is now there.
